### ISSUE TITLE
./pmInstall.sh: line 5: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by susdevlop** [PrimusLV/PM-Installer#1]
[mc@SusLinux ~]$ ls
pmInstall.sh
[mc@SusLinux ~]$ chmod +x ./pmInstall.sh
chmod: changing permissions of `./pmInstall.sh': Operation not permitted
[mc@SusLinux ~]$ ./pmInstall.sh
./pmInstall.sh: line 5: syntax error near unexpected token`newline'
./pmInstall.sh: line 5: `<!DOCTYPE html>'

**Comment by PrimusLV** [comment]
It should be fixed now ;)
